# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python27:
      python.version: '2.7'
    # Python35:
    #   python.version: '3.5'
    # Python36:
    #   python.version: '3.6'
    # Python37:
    #   python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- task: PowerShell@2
  inputs:
    filePath: './publish.ps1'
  displayName: 'Publish to artifacts directory'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './artifacts'
    ArtifactName: 'Screensaver.Client.Python'
    publishLocation: 'Container'

# - task: ArchiveFiles@2
#   inputs:
#     rootFolderOrFile: '$(Build.Repository.LocalPath)/artifacts'
#     includeRootFolder: false
#     archiveType: 'zip'
#     archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
#     replaceExistingArchive: true

